apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: licenseservice
  namespace: hawaiki-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: licenseservice
    spec:
      containers:
      - name: licenseservice-app
        image: sirwhitemonkey/licenseservice
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:${jhipster.registry.password}@jhipster-registry.hawaiki-demo.svc.cluster.local:8761/config
        - name: JHIPSTER_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: registry-admin-password
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:${jhipster.registry.password}@jhipster-registry.hawaiki-demo.svc.cluster.local:8761/eureka/
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://licenseservice-postgresql.hawaiki-demo.svc.cluster.local:5432/LicenseService
        - name: JAVA_OPTS
          value: " -Xmx256m -Xms256m"
        #resources:
        #  requests:
        #    memory: "256Mi"
        #    cpu: "500m"
        #  limits:
        #    memory: "512Mi"
        #    cpu: "1"
        ports:
        - name: web
          containerPort: 9002
        readinessProbe:
          httpGet:
            path: /management/health
            port: web
        livenessProbe:
          httpGet:
            path: /management/health
            port: web
          initialDelaySeconds: 180

